--PROBAR EL PROCEDIMIENTO CIN NETBEANS 
--EJEMPLO DE UNA TABLA Y SU PROCEDIMIENTO ALMACENADO PARA GUARDAR CON PK IMPUESTO O ARTIFICIAL

CREATE TABLE CALIFICACIONES (ID_CALIFICACION INTEGER, MATERIA VARCHAR2(80), VALOR FLOAT,
CONSTRAINT PK_ID_CAL PRIMARY KEY (ID_CALIFICACION));

--GENERAMOS UNA SECUENCIA
CREATE SEQUENCE SEC_CALIFICACIONES
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

--AQUI YA VIENE EL PROCEDIMIENTO!!!!
CREATE OR REPLACE PROCEDURE GUARDAR_CALIFICACIONES(MY_ID_CALIFICACION OUT INTEGER, MY_MATERIA INT VARCHAR2, MY_VALOR IN FLOAT)
AS 
BEGIN 
SELECT SEC_CALIFICACIONES.NEXTVAL INTO MY_ID_CALIFICACION FROM DUAL;
INSERT INTO CALIFICACIONES VALUES (MY_ID_CALIFICACION, MY_MATERIA, MY_VALOR));
END;
/

--PROBANDO PROCEDIMIENTO
DECLARE
VALOR INTEGER;
BEGIN GUARDAR_CALIFICACIONES(VALOR, '', 7)
END;
/

--VERIFICAMOS
SELECT * FROM CALIFICACIONES;
DELETE FROM CALIFICACIONES; --RELACIONADO A UN CURSOR EXPLICITO
DELETE FROM CALIFICACIONES WHERE ID_CALIFICACION=2;
SELECT COUNT (*) FROM CALIFICACIONES; --RELACIONADO A UN CURSOR IMPLICITO


--CURSORES EXPLICITOS: ES CUALQUIER SENTENCIA QUE OBTENGA COMO RESULTADO UNA O MAS FILAS.
--EJEMPLO SELECT * FROM CALIFICACIONES 
--SELECT * FROM CALIFICACIONES WHERE ID_CALIFICACION=1;

--EJEMPLO DE CURSOR EXPLICITO CON LA TABLA CALIFICACIONES

DECLARE 
CURSOR CUR_CALIF IS SELECT * FROM CALIFICACIONES;
BEGIN
FOR REC IN CUR_CALIF LOOP
DBMS_OUTPUT.PUT_LINE('EJEMPLO DE CURSOR EXPLICITO'||REC.VALOR|| 'MATERIA' || REC.MATERIA);
END LOOP;
END;
 /
 SET SEVEROUTPUT ON;
 



